//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HumanResources
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Company.
    /// </summary>
    // *** Start programmer edit section *** (Company CustomAttributes)

    // *** End programmer edit section *** (Company CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CompanyE", new string[] {
            "Name as \'Name\'"})]
    [AssociatedDetailViewAttribute("CompanyE", "Staff", "PersonE", true, "", "Staff", true, new string[] {
            ""})]
    [View("CompanyL", new string[] {
            "Name as \'Name\'"})]
    public class Company : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private IIS.HumanResources.DetailArrayOfPerson fStaff;
        
        // *** Start programmer edit section *** (Company CustomMembers)

        // *** End programmer edit section *** (Company CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Company.Name CustomAttributes)

        // *** End programmer edit section *** (Company.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Company.Name Get start)

                // *** End programmer edit section *** (Company.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Company.Name Get end)

                // *** End programmer edit section *** (Company.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Company.Name Set start)

                // *** End programmer edit section *** (Company.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Company.Name Set end)

                // *** End programmer edit section *** (Company.Name Set end)
            }
        }
        
        /// <summary>
        /// Company.
        /// </summary>
        // *** Start programmer edit section *** (Company.Staff CustomAttributes)

        // *** End programmer edit section *** (Company.Staff CustomAttributes)
        public virtual IIS.HumanResources.DetailArrayOfPerson Staff
        {
            get
            {
                // *** Start programmer edit section *** (Company.Staff Get start)

                // *** End programmer edit section *** (Company.Staff Get start)
                if ((this.fStaff == null))
                {
                    this.fStaff = new IIS.HumanResources.DetailArrayOfPerson(this);
                }
                IIS.HumanResources.DetailArrayOfPerson result = this.fStaff;
                // *** Start programmer edit section *** (Company.Staff Get end)

                // *** End programmer edit section *** (Company.Staff Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Company.Staff Set start)

                // *** End programmer edit section *** (Company.Staff Set start)
                this.fStaff = value;
                // *** Start programmer edit section *** (Company.Staff Set end)

                // *** End programmer edit section *** (Company.Staff Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "CompanyE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CompanyE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CompanyE", typeof(IIS.HumanResources.Company));
                }
            }
            
            /// <summary>
            /// "CompanyL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CompanyL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CompanyL", typeof(IIS.HumanResources.Company));
                }
            }
        }
    }
}
